package nivance.fundimpl.enums;

public enum CommandType {
	CREDITADJUSTCOMMAND,
	RETRIVEFUNDFLOW,
	OPENACCOUNTCOMMAND,
	RECHARGECOMMAND,
	RETRIVEBALANCECOMMAND,
	REWARDCOMMAND,
	SELLAMOUNTADJUSTCOMMAND,
	WAGERCOMMAND,
	WITHDRAWCOMMAND,
}
