package nivance.jpa.mysql.admin.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import nivance.jpa.mysql.entity.AdminOperator;
import nivance.jpa.mysql.entity.AdminOperatorExample;
import nivance.jpa.mysql.entity.AdminOperatorExample.Criteria;
import nivance.jpa.mysql.entity.AdminOperatorExample.Criterion;

public class AdminOperatorSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String countByExample(AdminOperatorExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("T_ADMIN_OPERATOR");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String deleteByExample(AdminOperatorExample example) {
        BEGIN();
        DELETE_FROM("T_ADMIN_OPERATOR");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String insertSelective(AdminOperator record) {
        BEGIN();
        INSERT_INTO("T_ADMIN_OPERATOR");
        
        if (record.getUsername() != null) {
            VALUES("USERNAME", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            VALUES("PASSWORD", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getRealname() != null) {
            VALUES("REALNAME", "#{realname,jdbcType=VARCHAR}");
        }
        
        if (record.getRetry() != null) {
            VALUES("RETRY", "#{retry,jdbcType=DECIMAL}");
        }
        
        if (record.getStatus() != null) {
            VALUES("STATUS", "#{status,jdbcType=DECIMAL}");
        }
        
        if (record.getCreatedate() != null) {
            VALUES("CREATEDATE", "#{createdate,jdbcType=DECIMAL}");
        }
        
        if (record.getLastdate() != null) {
            VALUES("LASTDATE", "#{lastdate,jdbcType=DECIMAL}");
        }
        
        if (record.getRolecode() != null) {
            VALUES("ROLECODE", "#{rolecode,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String selectByExample(AdminOperatorExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("USERNAME");
        } else {
            SELECT("USERNAME");
        }
        SELECT("PASSWORD");
        SELECT("REALNAME");
        SELECT("RETRY");
        SELECT("STATUS");
        SELECT("CREATEDATE");
        SELECT("LASTDATE");
        SELECT("ROLECODE");
        FROM("T_ADMIN_OPERATOR");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AdminOperator record = (AdminOperator) parameter.get("record");
        AdminOperatorExample example = (AdminOperatorExample) parameter.get("example");
        
        BEGIN();
        UPDATE("T_ADMIN_OPERATOR");
        
        if (record.getUsername() != null) {
            SET("USERNAME = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            SET("PASSWORD = #{record.password,jdbcType=VARCHAR}");
        }
        
        if (record.getRealname() != null) {
            SET("REALNAME = #{record.realname,jdbcType=VARCHAR}");
        }
        
        if (record.getRetry() != null) {
            SET("RETRY = #{record.retry,jdbcType=DECIMAL}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{record.status,jdbcType=DECIMAL}");
        }
        
        if (record.getCreatedate() != null) {
            SET("CREATEDATE = #{record.createdate,jdbcType=DECIMAL}");
        }
        
        if (record.getLastdate() != null) {
            SET("LASTDATE = #{record.lastdate,jdbcType=DECIMAL}");
        }
        
        if (record.getRolecode() != null) {
            SET("ROLECODE = #{record.rolecode,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("T_ADMIN_OPERATOR");
        
        SET("USERNAME = #{record.username,jdbcType=VARCHAR}");
        SET("PASSWORD = #{record.password,jdbcType=VARCHAR}");
        SET("REALNAME = #{record.realname,jdbcType=VARCHAR}");
        SET("RETRY = #{record.retry,jdbcType=DECIMAL}");
        SET("STATUS = #{record.status,jdbcType=DECIMAL}");
        SET("CREATEDATE = #{record.createdate,jdbcType=DECIMAL}");
        SET("LASTDATE = #{record.lastdate,jdbcType=DECIMAL}");
        SET("ROLECODE = #{record.rolecode,jdbcType=VARCHAR}");
        
        AdminOperatorExample example = (AdminOperatorExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String updateByPrimaryKeySelective(AdminOperator record) {
        BEGIN();
        UPDATE("T_ADMIN_OPERATOR");
        
        if (record.getPassword() != null) {
            SET("PASSWORD = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getRealname() != null) {
            SET("REALNAME = #{realname,jdbcType=VARCHAR}");
        }
        
        if (record.getRetry() != null) {
            SET("RETRY = #{retry,jdbcType=DECIMAL}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{status,jdbcType=DECIMAL}");
        }
        
        if (record.getCreatedate() != null) {
            SET("CREATEDATE = #{createdate,jdbcType=DECIMAL}");
        }
        
        if (record.getLastdate() != null) {
            SET("LASTDATE = #{lastdate,jdbcType=DECIMAL}");
        }
        
        if (record.getRolecode() != null) {
            SET("ROLECODE = #{rolecode,jdbcType=VARCHAR}");
        }
        
        WHERE("USERNAME = #{username,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    protected void applyWhere(AdminOperatorExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}