package nivance.serialize.test.bean;

import java.math.BigDecimal;
import org.apache.avro.reflect.Nullable;

public class AccAccountB extends AccAccountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.AMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.CREDITAMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private Long creditamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.MAXSALEAMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private Long maxsaleamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.UPDATEDATE
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private Long updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.EXTRAFIELD1
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private String extrafield1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.EXTRAFIELD2
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private String extrafield2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.EXTRAFIELD3
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private Integer extrafield3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.EXTRAFIELD4
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private BigDecimal extrafield4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.EXTRAFIELD5
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private Long extrafield5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.AMOUNT
     *
     * @return the value of T_ACC_ACCOUNT.AMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.AMOUNT
     *
     * @param amount the value for T_ACC_ACCOUNT.AMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.CREDITAMOUNT
     *
     * @return the value of T_ACC_ACCOUNT.CREDITAMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public Long getCreditamount() {
        return creditamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.CREDITAMOUNT
     *
     * @param creditamount the value for T_ACC_ACCOUNT.CREDITAMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setCreditamount(Long creditamount) {
        this.creditamount = creditamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.MAXSALEAMOUNT
     *
     * @return the value of T_ACC_ACCOUNT.MAXSALEAMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public Long getMaxsaleamount() {
        return maxsaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.MAXSALEAMOUNT
     *
     * @param maxsaleamount the value for T_ACC_ACCOUNT.MAXSALEAMOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setMaxsaleamount(Long maxsaleamount) {
        this.maxsaleamount = maxsaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.UPDATEDATE
     *
     * @return the value of T_ACC_ACCOUNT.UPDATEDATE
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public Long getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.UPDATEDATE
     *
     * @param updatedate the value for T_ACC_ACCOUNT.UPDATEDATE
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setUpdatedate(Long updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.EXTRAFIELD1
     *
     * @return the value of T_ACC_ACCOUNT.EXTRAFIELD1
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public String getExtrafield1() {
        return extrafield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.EXTRAFIELD1
     *
     * @param extrafield1 the value for T_ACC_ACCOUNT.EXTRAFIELD1
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setExtrafield1(String extrafield1) {
        this.extrafield1 = extrafield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.EXTRAFIELD2
     *
     * @return the value of T_ACC_ACCOUNT.EXTRAFIELD2
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public String getExtrafield2() {
        return extrafield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.EXTRAFIELD2
     *
     * @param extrafield2 the value for T_ACC_ACCOUNT.EXTRAFIELD2
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setExtrafield2(String extrafield2) {
        this.extrafield2 = extrafield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.EXTRAFIELD3
     *
     * @return the value of T_ACC_ACCOUNT.EXTRAFIELD3
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public Integer getExtrafield3() {
        return extrafield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.EXTRAFIELD3
     *
     * @param extrafield3 the value for T_ACC_ACCOUNT.EXTRAFIELD3
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setExtrafield3(Integer extrafield3) {
        this.extrafield3 = extrafield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.EXTRAFIELD4
     *
     * @return the value of T_ACC_ACCOUNT.EXTRAFIELD4
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public BigDecimal getExtrafield4() {
        return extrafield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.EXTRAFIELD4
     *
     * @param extrafield4 the value for T_ACC_ACCOUNT.EXTRAFIELD4
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setExtrafield4(BigDecimal extrafield4) {
        this.extrafield4 = extrafield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.EXTRAFIELD5
     *
     * @return the value of T_ACC_ACCOUNT.EXTRAFIELD5
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public Long getExtrafield5() {
        return extrafield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.EXTRAFIELD5
     *
     * @param extrafield5 the value for T_ACC_ACCOUNT.EXTRAFIELD5
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setExtrafield5(Long extrafield5) {
        this.extrafield5 = extrafield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACC_ACCOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccAccountB other = (AccAccountB) that;
        return (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCreditamount() == null ? other.getCreditamount() == null : this.getCreditamount().equals(other.getCreditamount()))
            && (this.getMaxsaleamount() == null ? other.getMaxsaleamount() == null : this.getMaxsaleamount().equals(other.getMaxsaleamount()))
            && (this.getUpdatedate() == null ? other.getUpdatedate() == null : this.getUpdatedate().equals(other.getUpdatedate()))
            && (this.getExtrafield1() == null ? other.getExtrafield1() == null : this.getExtrafield1().equals(other.getExtrafield1()))
            && (this.getExtrafield2() == null ? other.getExtrafield2() == null : this.getExtrafield2().equals(other.getExtrafield2()))
            && (this.getExtrafield3() == null ? other.getExtrafield3() == null : this.getExtrafield3().equals(other.getExtrafield3()))
            && (this.getExtrafield4() == null ? other.getExtrafield4() == null : this.getExtrafield4().equals(other.getExtrafield4()))
            && (this.getExtrafield5() == null ? other.getExtrafield5() == null : this.getExtrafield5().equals(other.getExtrafield5()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACC_ACCOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCreditamount() == null) ? 0 : getCreditamount().hashCode());
        result = prime * result + ((getMaxsaleamount() == null) ? 0 : getMaxsaleamount().hashCode());
        result = prime * result + ((getUpdatedate() == null) ? 0 : getUpdatedate().hashCode());
        result = prime * result + ((getExtrafield1() == null) ? 0 : getExtrafield1().hashCode());
        result = prime * result + ((getExtrafield2() == null) ? 0 : getExtrafield2().hashCode());
        result = prime * result + ((getExtrafield3() == null) ? 0 : getExtrafield3().hashCode());
        result = prime * result + ((getExtrafield4() == null) ? 0 : getExtrafield4().hashCode());
        result = prime * result + ((getExtrafield5() == null) ? 0 : getExtrafield5().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACC_ACCOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", amount=").append(amount);
        sb.append(", creditamount=").append(creditamount);
        sb.append(", maxsaleamount=").append(maxsaleamount);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", extrafield1=").append(extrafield1);
        sb.append(", extrafield2=").append(extrafield2);
        sb.append(", extrafield3=").append(extrafield3);
        sb.append(", extrafield4=").append(extrafield4);
        sb.append(", extrafield5=").append(extrafield5);
        sb.append("]");
        return sb.toString();
    }
}