package nivance.serialize.test.bean;

import org.apache.avro.reflect.Nullable;

public class AccAccountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACC_ACCOUNT.MERCHANTID
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Nullable
    private String merchantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACC_ACCOUNT.MERCHANTID
     *
     * @return the value of T_ACC_ACCOUNT.MERCHANTID
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACC_ACCOUNT.MERCHANTID
     *
     * @param merchantid the value for T_ACC_ACCOUNT.MERCHANTID
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACC_ACCOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccAccountKey other = (AccAccountKey) that;
        return (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACC_ACCOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACC_ACCOUNT
     *
     * @mbggenerated Thu Apr 03 15:23:08 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantid=").append(merchantid);
        sb.append("]");
        return sb.toString();
    }
}