package nivance.jpa.mysql.entity;


public class AdminOperator extends AdminOperatorKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.PASSWORD
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.REALNAME
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.RETRY
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private Short retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.STATUS
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.CREATEDATE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private Long createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.LASTDATE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private Long lastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_OPERATOR.ROLECODE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    private String rolecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.PASSWORD
     *
     * @return the value of T_ADMIN_OPERATOR.PASSWORD
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.PASSWORD
     *
     * @param password the value for T_ADMIN_OPERATOR.PASSWORD
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.REALNAME
     *
     * @return the value of T_ADMIN_OPERATOR.REALNAME
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.REALNAME
     *
     * @param realname the value for T_ADMIN_OPERATOR.REALNAME
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.RETRY
     *
     * @return the value of T_ADMIN_OPERATOR.RETRY
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public Short getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.RETRY
     *
     * @param retry the value for T_ADMIN_OPERATOR.RETRY
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setRetry(Short retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.STATUS
     *
     * @return the value of T_ADMIN_OPERATOR.STATUS
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.STATUS
     *
     * @param status the value for T_ADMIN_OPERATOR.STATUS
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.CREATEDATE
     *
     * @return the value of T_ADMIN_OPERATOR.CREATEDATE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public Long getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.CREATEDATE
     *
     * @param createdate the value for T_ADMIN_OPERATOR.CREATEDATE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.LASTDATE
     *
     * @return the value of T_ADMIN_OPERATOR.LASTDATE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public Long getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.LASTDATE
     *
     * @param lastdate the value for T_ADMIN_OPERATOR.LASTDATE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setLastdate(Long lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_OPERATOR.ROLECODE
     *
     * @return the value of T_ADMIN_OPERATOR.ROLECODE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_OPERATOR.ROLECODE
     *
     * @param rolecode the value for T_ADMIN_OPERATOR.ROLECODE
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminOperator other = (AdminOperator) that;
        return (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()))
            && (this.getRetry() == null ? other.getRetry() == null : this.getRetry().equals(other.getRetry()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getLastdate() == null ? other.getLastdate() == null : this.getLastdate().equals(other.getLastdate()))
            && (this.getRolecode() == null ? other.getRolecode() == null : this.getRolecode().equals(other.getRolecode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        result = prime * result + ((getRetry() == null) ? 0 : getRetry().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getLastdate() == null) ? 0 : getLastdate().hashCode());
        result = prime * result + ((getRolecode() == null) ? 0 : getRolecode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_OPERATOR
     *
     * @mbggenerated Wed Aug 27 15:23:08 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", password=").append(password);
        sb.append(", realname=").append(realname);
        sb.append(", retry=").append(retry);
        sb.append(", status=").append(status);
        sb.append(", createdate=").append(createdate);
        sb.append(", lastdate=").append(lastdate);
        sb.append(", rolecode=").append(rolecode);
        sb.append("]");
        return sb.toString();
    }
}